.arm64:
  tags:
    - arm64-dind

stages:
  - build

build:
  stage: build
  extends: .arm64
  services:
      - docker:dind
  image: docker:20.10-dind
  tags:
    - saas-linux-medium-arm64
  script:
      - docker info
      - docker run ubuntu:latest 
